version: "3.9"
   
services:
  db:
    image: postgres
    container_name: mtccbdb
  redis:
    container_name: redis
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    volumes:
      - '.:/code'
    ports:
      - "8000:8000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

volumes:
  redisdata:
  db:
  .:
